#!/usr/bin/env python3
"""Generate the N-arm enum-match perm-cycle case.

Shape mirrors tests/cases/passing/permissions/enum_match_ref_mut_perm_cycle.vpr
(the Prusti translation of `fn add(v: &mut i32, case: Case)` matching on an
N-variant enum), parameterized by arm count. Each arm has TWO guarded
conversion cycles (read cycle in the compute block, write-back cycle in its
join-edge block) — the load-bearing part of the repro shape.

Usage: gen_enum_match.py N > out.vpr
"""
import sys

N = int(sys.argv[1])

DEREF = "p_Ref_mutable_snap(_1p, s_Int_i32_type()).s_Ref_mutable_0"

out = []
emit = out.append

emit(f"// GENERATED by gen_enum_match.py {N} — {N}-arm enum-match perm cycle.")
emit("// Do not edit by hand; regenerate instead.")

# --- domains (fixed) ---
emit("""
domain s_Param {}

domain s_Int_i32 {
  function s_Int_i32_cons(arg0: Int): s_Int_i32
  function s_Int_i32_value(arg0: s_Int_i32): Int
  axiom s_Int_i32_ax_cons {
    (forall s: s_Int_i32 :: { s_Int_i32_value(s) }
      s_Int_i32_cons(s_Int_i32_value(s)) == s)
  }
  axiom s_Int_i32_ax_bounds {
    (forall s: s_Int_i32 :: { s_Int_i32_value(s) }
      -2147483648 <= s_Int_i32_value(s) && s_Int_i32_value(s) <= 2147483647)
  }
  axiom s_Int_i32_ax_value {
    (forall value: Int :: { s_Int_i32_cons(value) }
      -2147483648 <= value && value <= 2147483647 ==>
      s_Int_i32_value(s_Int_i32_cons(value)) == value)
  }
}

domain s_Int_isize {
  function s_Int_isize_cons(arg0: Int): s_Int_isize
  function s_Int_isize_value(arg0: s_Int_isize): Int
  axiom s_Int_isize_ax_cons {
    (forall s: s_Int_isize :: { s_Int_isize_value(s) }
      s_Int_isize_cons(s_Int_isize_value(s)) == s)
  }
  axiom s_Int_isize_ax_bounds {
    (forall s: s_Int_isize :: { s_Int_isize_value(s) }
      -9223372036854775808 <= s_Int_isize_value(s) &&
      s_Int_isize_value(s) <= 9223372036854775807)
  }
  axiom s_Int_isize_ax_value {
    (forall value: Int :: { s_Int_isize_cons(value) }
      -9223372036854775808 <= value && value <= 9223372036854775807 ==>
      s_Int_isize_value(s_Int_isize_cons(value)) == value)
  }
}

domain s_Bool {
  function s_Bool_cons(arg0: Bool): s_Bool
  function s_Bool_value(arg0: s_Bool): Bool
  axiom s_Bool_ax_cons {
    (forall s: s_Bool :: { s_Bool_value(s) }
      s_Bool_cons(s_Bool_value(s)) == s)
  }
  axiom s_Bool_ax_value {
    (forall value: Bool :: { s_Bool_cons(value) }
      s_Bool_value(s_Bool_cons(value)) == value)
  }
}

domain TypeOf {
  function s_Int_i32_typeof(arg0: s_Int_i32): Type
  function s_Param_typeof(arg0: s_Param): Type
  function s_0_Tuple_typeof(arg0: s_0_Tuple): Type
  function s_Bool_typeof(arg0: s_Bool): Type
}

field p_Ref_mutable_val: s_Ref_mutable
field p_Int_i32_val: s_Int_i32
field p_Int_isize_val: s_Int_isize
field p_Bool_val: s_Bool

function mir_binop_AddWithOverflow_Int_i32_Int_i32(arg1: s_Int_i32, arg2: s_Int_i32): s_2_Tuple
{
  (let val ==
    (s_Int_i32_value(arg1) + s_Int_i32_value(arg2)) in
    (let wrapped_val ==
      ((val + 2147483648) % 4294967296 - 2147483648) in
      s_2_Tuple_cons(make_generic_s_Int_i32(s_Int_i32_cons(wrapped_val)), make_generic_s_Bool(s_Bool_cons(wrapped_val !=
      val)))))
}

function make_generic_s_Int_i32(self: s_Int_i32): s_Param
  ensures s_Param_typeof(result) == s_Int_i32_type()
  ensures make_concrete_s_Int_i32(result) == self

function make_concrete_s_Int_i32(snap: s_Param): s_Int_i32
  ensures make_generic_s_Int_i32(result) == snap

function make_generic_s_0_Tuple(self: s_0_Tuple): s_Param
  ensures s_Param_typeof(result) == s_0_Tuple_type()
  ensures make_concrete_s_0_Tuple(result) == self

function make_concrete_s_0_Tuple(snap: s_Param): s_0_Tuple
  ensures make_generic_s_0_Tuple(result) == snap

function make_generic_s_Bool(self: s_Bool): s_Param
  ensures s_Param_typeof(result) == s_Bool_type()
  ensures make_concrete_s_Bool(result) == self

function make_concrete_s_Bool(snap: s_Param): s_Bool
  ensures make_generic_s_Bool(result) == snap

function s_0_Tuple_unreachable(): s_0_Tuple
  ensures false

function s_Param_unreachable(T$0: Type): s_Param
  ensures false

function s_Ref_mutable_unreachable(U$1: Type): s_Ref_mutable
  ensures false

function s_Int_i32_unreachable(): s_Int_i32
  ensures false

function s_Int_isize_unreachable(): s_Int_isize
  ensures false

function s_Case_unreachable(): s_Case
  ensures false

function s_Bool_unreachable(): s_Bool
  ensures false

function s_2_Tuple_unreachable(T$0: Type, U$1: Type): s_2_Tuple
  ensures false

function s_2_Tuple_field_0(self: Ref, T$0: Type, U$1: Type): Ref
  ensures (self == null) == (result == null)

function s_2_Tuple_field_1(self: Ref, T$0: Type, U$1: Type): Ref
  ensures (self == null) == (result == null)

function p_0_Tuple_snap(self: Ref): s_0_Tuple
  requires acc(p_0_Tuple(self), write)
{
  (unfolding acc(p_0_Tuple(self), write) in s_0_Tuple_cons())
}

function p_Param_snap(self: Ref, T$0: Type): s_Param
  requires acc(p_Param(self, T$0), write)

function p_Ref_mutable_arbitrary_value(r: Ref, metadata: s_Param): s_Ref_mutable
  ensures result.s_Ref_mutable_0 == r
  ensures result.s_Ref_mutable_1 == metadata

function p_Ref_mutable_snap(self: Ref, U$1: Type): s_Ref_mutable
  requires acc(p_Ref_mutable(self, U$1), write)
{
  (unfolding acc(p_Ref_mutable(self, U$1), write) in
    self.p_Ref_mutable_val)
}

function p_Int_i32_snap(self: Ref): s_Int_i32
  requires acc(p_Int_i32(self), write)
{
  (unfolding acc(p_Int_i32(self), write) in self.p_Int_i32_val)
}

function p_Int_isize_snap(self: Ref): s_Int_isize
  requires acc(p_Int_isize(self), write)
{
  (unfolding acc(p_Int_isize(self), write) in self.p_Int_isize_val)
}

function p_Case_field_discr(self: Ref): Ref
  ensures (self == null) == (result == null)

function p_2_Tuple_snap(self: Ref, T$0: Type, U$1: Type): s_2_Tuple
  requires acc(p_2_Tuple(self, T$0, U$1), write)
{
  (unfolding acc(p_2_Tuple(self, T$0, U$1), write) in
    s_2_Tuple_cons(p_Param_snap(s_2_Tuple_field_0(self, T$0, U$1), T$0), p_Param_snap(s_2_Tuple_field_1(self,
    T$0, U$1), U$1)))
}

function p_Bool_snap(self: Ref): s_Bool
  requires acc(p_Bool(self), write)
{
  (unfolding acc(p_Bool(self), write) in self.p_Bool_val)
}
""")

# --- s_Case_discr: nested ite over N variants ---
body = "s_Int_isize_cons(0)"
for k in range(1, N):
    pass
# build innermost-out: highest variant outermost, mirroring the source file
expr = "s_Int_isize_cons(0)"
for k in range(1, N):
    expr = f"(self.iss_Case_{k}_cons ? s_Int_isize_cons({k}) : {expr})"
emit(f"""function s_Case_discr(self: s_Case): s_Int_isize
{{
  {expr}
}}
""")

# --- p_Case_snap: nested unfolding pick ---
snap_expr = "s_Case_unreachable()"
for k in range(N):
    # innermost = variant 0 last, like the source (3,2,1,0)
    pass
for k in range(N):
    snap_expr = (
        f"(p_Int_isize_snap(p_Case_field_discr(self)) == s_Int_isize_cons({k}) ? "
        f"(unfolding acc(p_Case_{k}_owned(self), write) in s_Case_{k}_cons()) : {snap_expr})"
    )
emit(f"""function p_Case_snap(self: Ref): s_Case
  requires acc(p_Case(self), write)
{{
  (unfolding acc(p_Case(self), write) in
    {snap_expr})
}}
""")

# --- predicates ---
emit("predicate p_0_Tuple(self: Ref) { true }\n")
emit("predicate p_Param(self: Ref, T$0: Type)\n")
emit("predicate p_Ref_mutable(self: Ref, U$1: Type) { acc(self.p_Ref_mutable_val, write) }\n")
emit("predicate p_Int_i32(self: Ref) { acc(self.p_Int_i32_val, write) }\n")
emit("predicate p_Int_isize(self: Ref) { acc(self.p_Int_isize_val, write) }\n")
for k in range(N):
    emit(f"predicate p_Case_{k}_owned(self: Ref) {{ true }}\n")

discr = "p_Int_isize_snap(p_Case_field_discr(self))"
disj = " || ".join(f"{discr} == s_Int_isize_cons({k})" for k in range(N))
owned = " &&\n  ".join(
    f"({discr} == s_Int_isize_cons({k}) ==> acc(p_Case_{k}_owned(self), write))"
    for k in range(N)
)
emit(f"""predicate p_Case(self: Ref) {{
  acc(p_Int_isize(p_Case_field_discr(self)), write) &&
  (({disj}) &&
  ({owned}))
}}
""")

emit("""predicate p_2_Tuple(self: Ref, T$0: Type, U$1: Type) {
  acc(p_Param(s_2_Tuple_field_0(self, T$0, U$1), T$0), write) &&
  acc(p_Param(s_2_Tuple_field_1(self, T$0, U$1), U$1), write)
}

predicate p_Bool(self: Ref) { acc(self.p_Bool_val, write) }
""")

# --- method m_add ---
emit("method m_add(_0p: Ref, _1p: Ref, _2p: Ref)")
emit("  requires acc(p_Ref_mutable(_1p, s_Int_i32_type()), write)")
emit("  requires acc(p_Case(_2p), write)")
emit(f"  requires acc(p_Param({DEREF},")
emit("    s_Int_i32_type()), write)")
emit("  ensures acc(p_0_Tuple(_0p), write)")
emit("  ensures acc(p_Param(old(p_Ref_mutable_snap(_1p, s_Int_i32_type())).s_Ref_mutable_0,")
emit("    s_Int_i32_type()), write)")
emit("{")
emit("  var _3p: Ref")
for k in range(N):
    emit(f"  var _a{k}p: Ref")   # per-arm copy of *v
    emit(f"  var _b{k}p: Ref")   # per-arm overflow tuple
emit("  var _from_bb0_to_unreach: Bool")
for k in range(N):
    emit(f"  var _from_bb0_to_arm{k}: Bool")
    emit(f"  var _from_arm{k}_to_wb{k}: Bool")
    emit(f"  var _from_wb{k}_to_join: Bool")
emit("  var _tmp0: s_Int_isize")
for k in range(N):
    emit(f"  var _ovf{k}: s_Bool")
    emit(f"  var _res{k}: s_Int_i32")
emit("  label start")
emit("  _from_bb0_to_unreach := false")
for k in range(N):
    emit(f"  _from_bb0_to_arm{k} := false")
    emit(f"  _from_arm{k}_to_wb{k} := false")
    emit(f"  _from_wb{k}_to_join := false")
emit("  goto bb_0")
emit("  label bb_0")
emit("  p_Int_isize_assign(_3p, (unfolding acc(p_Case(_2p)) in")
emit("      p_Int_isize_snap(p_Case_field_discr(_2p))))")
emit("  _tmp0 := p_Int_isize_snap(_3p)")
emit("  exhale acc(p_Int_isize(_3p), write)")
for k in range(N):
    kw = "if" if k == 0 else "} elseif"
    emit(f"  {kw} (s_Int_isize_value(_tmp0) == {k}) {{")
    emit(f"    _from_bb0_to_arm{k} := true")
    emit(f"    goto arm_{k}")
emit("  } else {")
emit("    _from_bb0_to_unreach := true")
emit("    goto bb_unreach")
emit("  }")

emit("  label bb_unreach")
emit("  exhale false")
emit("  inhale false")
emit("  goto end")

for k in range(N):
    c = k + 1  # the added constant
    emit(f"  label arm_{k}")
    # read conversion cycle (cycle 1)
    emit(f"  if (_from_bb0_to_arm{k}) {{")
    emit(f"    make_concrete_Int_i32({DEREF})")
    emit("  }")
    emit(f"  p_Int_i32_assign(_a{k}p, p_Int_i32_snap({DEREF}))")
    emit(f"  if (_from_bb0_to_arm{k}) {{")
    emit(f"    make_generic_Int_i32({DEREF})")
    emit("  }")
    emit(f"  p_2_Tuple_assign(_b{k}p, s_Int_i32_type(), s_Bool_type(), mir_binop_AddWithOverflow_Int_i32_Int_i32(p_Int_i32_snap(_a{k}p),")
    emit(f"    s_Int_i32_cons({c})))")
    emit(f"  unfold acc(p_2_Tuple(_b{k}p, s_Int_i32_type(), s_Bool_type()), write)")
    emit(f"  make_concrete_Int_i32(s_2_Tuple_field_0(_b{k}p, s_Int_i32_type(), s_Bool_type()))")
    emit(f"  make_concrete_Bool(s_2_Tuple_field_1(_b{k}p, s_Int_i32_type(), s_Bool_type()))")
    emit(f"  _ovf{k} := p_Bool_snap(s_2_Tuple_field_1(_b{k}p, s_Int_i32_type(), s_Bool_type()))")
    emit(f"  exhale acc(p_Bool(s_2_Tuple_field_1(_b{k}p, s_Int_i32_type(), s_Bool_type())), write)")
    emit(f"  inhale s_Bool_value(_ovf{k}) == false")
    emit(f"  _from_arm{k}_to_wb{k} := true")
    emit(f"  goto wb_{k}")

for k in range(N):
    emit(f"  label wb_{k}")
    # write-back conversion cycle (cycle 2)
    emit(f"  if (_from_bb0_to_arm{k}) {{")
    emit(f"    make_concrete_Int_i32({DEREF})")
    emit("  }")
    emit(f"  exhale acc(p_Int_i32({DEREF}), write)")
    emit(f"  _res{k} := p_Int_i32_snap(s_2_Tuple_field_0(_b{k}p, s_Int_i32_type(), s_Bool_type()))")
    emit(f"  exhale acc(p_Int_i32(s_2_Tuple_field_0(_b{k}p, s_Int_i32_type(), s_Bool_type())), write)")
    emit(f"  p_Int_i32_assign({DEREF},")
    emit(f"    _res{k})")
    emit(f"  if (_from_bb0_to_arm{k}) {{")
    emit(f"    make_generic_Int_i32({DEREF})")
    emit("  }")
    emit("  p_0_Tuple_assign(_0p, s_0_Tuple_cons())")
    emit(f"  _from_wb{k}_to_join := true")
    emit("  goto bb_join")

emit("  label bb_join")
emit("  goto end")
emit("  label end")
emit("}")

# --- helper methods + adts (fixed) ---
emit("""
method make_generic_Int_i32(self: Ref)
  requires acc(p_Int_i32(self), write)
  ensures acc(p_Param(self, s_Int_i32_type()), write)
  ensures old(make_generic_s_Int_i32(p_Int_i32_snap(self))) ==
    p_Param_snap(self, s_Int_i32_type())

method make_concrete_Int_i32(self: Ref)
  requires acc(p_Param(self, s_Int_i32_type()), write)
  ensures acc(p_Int_i32(self), write)
  ensures old(p_Param_snap(self, s_Int_i32_type())) ==
    make_generic_s_Int_i32(p_Int_i32_snap(self))

method make_generic_Bool(self: Ref)
  requires acc(p_Bool(self), write)
  ensures acc(p_Param(self, s_Bool_type()), write)
  ensures old(make_generic_s_Bool(p_Bool_snap(self))) ==
    p_Param_snap(self, s_Bool_type())

method make_concrete_Bool(self: Ref)
  requires acc(p_Param(self, s_Bool_type()), write)
  ensures acc(p_Bool(self), write)
  ensures old(p_Param_snap(self, s_Bool_type())) ==
    make_generic_s_Bool(p_Bool_snap(self))

method p_0_Tuple_assign(self: Ref, value: s_0_Tuple)
  ensures acc(p_0_Tuple(self), write)
  ensures p_0_Tuple_snap(self) == value

method p_Param_assign(self: Ref, T$0: Type, value: s_Param)
  ensures acc(p_Param(self, T$0), write)
  ensures p_Param_snap(self, T$0) == value

method p_Ref_mutable_assign(self: Ref, U$1: Type, value: s_Ref_mutable)
  ensures acc(p_Ref_mutable(self, U$1), write)
  ensures p_Ref_mutable_snap(self, U$1) == value

method p_Int_i32_assign(self: Ref, value: s_Int_i32)
  ensures acc(p_Int_i32(self), write)
  ensures p_Int_i32_snap(self) == value

method p_Int_isize_assign(self: Ref, value: s_Int_isize)
  ensures acc(p_Int_isize(self), write)
  ensures p_Int_isize_snap(self) == value

method p_Case_assign(self: Ref, value: s_Case)
  ensures acc(p_Case(self), write)
  ensures p_Case_snap(self) == value

method p_2_Tuple_assign(self: Ref, T$0: Type, U$1: Type, value: s_2_Tuple)
  ensures acc(p_2_Tuple(self, T$0, U$1), write)
  ensures p_2_Tuple_snap(self, T$0, U$1) == value

method p_Bool_assign(self: Ref, value: s_Bool)
  ensures acc(p_Bool(self), write)
  ensures p_Bool_snap(self) == value

adt s_0_Tuple {
  s_0_Tuple_cons()
}

adt s_Ref_mutable {
  s_Ref_mutable_cons(s_Ref_mutable_0: Ref, s_Ref_mutable_1: s_Param, s_Ref_mutable_2: s_Param)
}
""")

emit("adt s_Case {")
for k in range(N):
    emit(f"  s_Case_{k}_cons()")
emit("}")

emit("""
adt s_2_Tuple {
  s_2_Tuple_cons(s_2_Tuple_0: s_Param, s_2_Tuple_1: s_Param)
}

adt Type {
  s_Int_i32_type()
  s_0_Tuple_type()
  s_Bool_type()
  Unknown_type(non_unit: Int)
}""")

print("\n".join(out))
